# Project information
site_name: API Design Guidelines
#site_description: 'A Material Design theme for MkDocs'
#site_author: 'Martin Donath'
#site_url: 'https://squidfunk.github.io/mkdocs-material/'

# Repository
#repo_name: 'squidfunk/mkdocs-material'
#repo_url: 'https://github.com/squidfunk/mkdocs-material'

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  logo: #imgs/logo.png
    icon: code
#   feature:
#     tabs: true

markdown_extensions:
- admonition
- codehilite:
    guess_lang: false
    linenums: false
- footnotes
- toc:
    permalink: true
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true

extra_css:
  - 'stylesheets/critic.css'

pages:
- Introduction: index.md
- APIs: apis.md
- REST: rest.md
- HTTP: http.md
- Resource Identifiers: resource_identifiers.md
- Resources: resources.md
- Methods: methods.md
- -Representations: representations.md
- -Hypermedia: hypermedia.md
- Content Negotiation: content_negotiation.md
- -Caching: caching.md
- -Security: security.md
- -Versioning and Extensibility: versioning_and_extensibility.md
- -Documentation and Discovery: documentation_and_discovery.md
- -Specifications: specifications.md
- -Mocking: mocking.md
- Clients: clients.md
- -Other topics: other_topics.md
- References: references.md
- Examples: examples.md

