site_name: API Design Guidelines
theme: readthedocs
pages:
- Introduction: 'index.md'
- APIs: 'apis.md'
- Uniform Interface: 'uniform_interface.md'
- Resource Identifiers: 'resource_identifiers.md'
- Resources: 'resources.md'
- Methods: 'methods.md'
- Representations: 'representations.md'
- Hypermedia: 'hypermedia.md'
- Content Negotiation: 'content_negotiation.md'
- Caching: 'caching.md'
- Security: 'security.md'
- Versioning and Extensibility: 'versioning_and_extensibility.md'
- Documentation and Discovery: 'documentation_and_discovery.md'
- Specifications: 'specifications.md'
- Mocking: 'mocking.md'
- Clients: 'clients.md'
- Other topics: 'other_topics.md'
- Misc: 'misc.md'
- References: 'references.md'
